all: roomba_oriented_programming

roomba_oriented_programming: roomba_oriented_programming.c
	gcc -o roomba_oriented_programming roomba_oriented_programming.c -fno-stack-protector -no-pie -O0

clean:
	rm -f roomba_oriented_programming
