services:
  builder:
    container_name: compile
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/src
    working_dir: /src
    stdin_open: true # docker run -i
    tty: true
